### ISSUE TITLE
Удаление папки проекта в Win

### ISSUE THREAD

**Issue by Ferym26** [agragregra/start_html#12]
Как удалить папку проекта, если в ней "node_modules" всегда имеет ниипическую вложенность и длина путей превышает 255 символов?

**Comment by anpleenko** [comment]
открываешь gitbush и пишешь 

```
rm -rf node_modules
```

**Comment by npofopr** [comment]
Да можно и в Проводнике удалить) Ещё быстрее чем через `rm -rf` получается.

**Comment by anpleenko** [comment]
винда не даст, вылетит окошко

**Comment by npofopr** [comment]
У меня всё даёт :-)

**Comment by anpleenko** [comment]
значит меньше 255 символов у вас пути

**Comment by Air-Petr** [comment]
Я через TotalCommaner удаляю: выбираешь папку node_module, нажимаешь "файлы"->"изменить атрибуты", отмечаешь самый первый чекбокс и снимаешь четыре чекбокса под ним, нажимаешь ок. Окно закрылось, нажимаешь Del. В гугле давно нашел это решение.

**Comment by Ferym26** [comment]
2 Air-Petr: 
Этот способ я тоже видел. у меня не работает в win10x64

2 vaeum:
не удаляет

```
rm: cannot remove directory `node_modules': Directory not empty
```

**Comment by Air-Petr** [comment]
Самый дикий способ: руками переименовывать все папки в "1", например. Когда длина пути станет меньше 255 символов всё удалиться. ТАК ДЕЛАТЬ НЕЛЬЗЯ (но если очень хочется, то можно)

**Comment by kkudryaev** [comment]
Программа Unlocker должна помочь.

**Comment by Ferym26** [comment]
2 novus57
[не помогла](http://c2n.me/3wNiUI0). пишет что удалила, а папка и вся радость внутри остается

**Comment by Ferym26** [comment]
2 novus57
[не помогла](http://c2n.me/3wNiUI0). пишет что удалила, а папка и вся радость внутри остается

**Comment by kkudryaev** [comment]
После перезагразки, просто захожу в папку ctrl + a, ctrl + d и все нормально, а потом папку удаляю.

**Comment by npofopr** [comment]
Мне кажется это в любом случае, никак не относится к данному репозиторию) 
В поддержку Windows лучше напишите) 
Да и в целом полно решений в сети http://www.nikola-breznjak.com/blog/nodejs/how-to-delete-node_modules-folder-on-windows-machine/
