### ISSUE TITLE
Git Error

### ISSUE THREAD

**Issue by alexstulov** [agragregra/start_html#2]
Пользую Webstrom, при добавлении файлов в репозиторий получаю следующее:
The following problems have occurred when adding the files:
fatal: LF would be replaced by CRLF in index.html
 during executing git -c core.quotepath=false add --ignore-errors -- index.html
Так везде, кроме, наверное, compiled.min.css.
Можно пофиксить так:
git config --global core.autocrlf false
git config --global core.safecrlf false

Возможно проблема только у меня.

**Comment by katsiarynahil** [comment]
ооо спасибо!

**Comment by npofopr** [comment]
Это же совсем не относится к шаблону)
